### ISSUE TITLE
How to use this scroll carousel with react application?

### ISSUE THREAD

**Issue by nazmul162001** [asif-jalil/scroll-carousel#32]
| Name | About | Labels |
| ------ | ------ | ------- |
|  📚 Documentation |  Report an issue related to documentation |  'documentation, needs triage' |

## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/asif-jalil/scroll-carousel/contributing.md)?

(Write your answer here.)

**Comment by asif-jalil** [comment]
In react initialize the carousel in `useEffect`. Then use it as usual according to our documentation.

```
import { useEffect } from "react";
import ScrollCarousel from "scroll-carousel";
import "scroll-carousel/dist/scroll.carousel.min.css";
import logo from "./logo.svg";

function App() {
  useEffect(() => {
    new ScrollCarousel(".carousel");
  }, []);

  return (
  <div className="carousel">
    <img src={logo}  alt="logo" />
    <img src={logo}  alt="logo" />
    <img src={logo}  alt="logo" />
    <img src={logo} alt="logo" />
    <img src={logo} alt="logo" />
    <img src={logo} alt="logo" />
    <img src={logo} alt="logo" />
  </div>
  )
}
```

**Comment by asif-jalil** [comment]
If your problem is solved, then close the issue please.

**Comment by nazmul162001** [comment]
Okay, I Checked this.

**Comment by nazmul162001** [comment]
Thank you bro. it's worked. Super
