### ISSUE TITLE
Can you please add this in Yarn

### ISSUE THREAD

**Issue by nomandhoni-cs** [asif-jalil/scroll-carousel#33]
| Name | About | Labels |
| ------ | ------ | ------- |
|  📚 Documentation |  Report an issue related to documentation |  'documentation, needs triage' |

## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/asif-jalil/scroll-carousel/contributing.md)?

(Write your answer here.)

**Comment by asif-jalil** [comment]
Hello @nomandhoni-cs,
Scroll carousel is already added to yarn. Please use `yarn add scroll-carousel`
