### ISSUE TITLE
How to use scroll carousel on Gatsby?

### ISSUE THREAD

**Issue by yansusanto** [asif-jalil/scroll-carousel#35]
```
	useEffect(() => {
		if (typeof window !== "undefined") {
			const initializationTimeout = setTimeout(() => {
				new ScrollCarousel(".carousel", {
					autoplay: true,
					smartSpeed: true,
					margin: 0,
				});
			}, 100);

			return () => {
				clearTimeout(initializationTimeout);
			};
		}
	}, []);
```

The above initialization works on development but I'm struggling with `"document" is not available during server-side rendering.` on `gatsby build`. 

I'm hoping someone may point me in the right direction.

**Comment by asif-jalil** [comment]
Let's try the react version of the scroll carousel. Hopefully, this problem will be kicked out. If there will be further issue, please let us know. 

https://github.com/asif-jalil/scroll-carousel-react

**Comment by yansusanto** [comment]
Thank you. I wasn't aware there is a react-version. That solves everything.

**Comment by yansusanto** [comment]
Thank you. I wasn't aware there is a react-version. That solves everything.
